codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        # basic
        target: 0
        threshold: 0
    patch:
      default:
        target: 0
        threshold: 0

ignore:
  - "wheres_waldo/tests/"
  - "wheres_waldo/due.py"
  - "wheres_waldo/_version.py"
  - "wheres_waldo/info.py"
